# Address failing osx build which started in 0.1.14
# https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.12"                # [osx and x86_64]
