{% set name = "ruff" %}
{% set version = "0.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16d717b1d57b2e2fd68bd0bf80fb43931b79d05a7131aa477d66fc40fbd86268

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - make
    - maturin
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin
    - toml
  run:
    - python

test:
  commands:
    - ruff --help
  imports:
    - ruff

about:
  home: https://github.com/charliermarsh/ruff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An extremely fast Python linter, written in Rust.

  # The remaining entries in this section are optional, but recommended.
  description: |
    An extremely fast Python linter, written in Rust. Ruff can be used to
    replace Flake8 (plus a variety of plugins), isort, pydocstyle, yesqa, and
    even a subset of pyupgrade and autoflake all while executing tens or
    hundreds of times faster than any individual tool.
  dev_url: https://github.com/charliermarsh/ruff

extra:
  recipe-maintainers:
    - zanieb
    - messense
    - charliermarsh
