# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.16.5"

package:
  name: ruff
  version: ${{ version }}

source:
  url: https://github.com/astral-sh/ruff/archive/refs/tags/${{ version }}.tar.gz
  sha256: c447968b1e608450c973d441fa87f949f676064aec2db458b557e8222a4eb252

build:
  number: 1
  script:
    env:
      JEMALLOC_SYS_WITH_LG_PAGE: ${{ '16' if aarch64 else '' }}
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path crates/ruff
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .\crates\ruff
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml\
      - if: unix
        then:
          - mkdir -p $PREFIX/share/zsh/site-functions $PREFIX/share/bash-completion/completions $PREFIX/share/fish/vendor_completions.d
          - $PREFIX/bin/ruff generate-shell-completion zsh > $PREFIX/share/zsh/site-functions/_ruff
          - $PREFIX/bin/ruff generate-shell-completion bash > $PREFIX/share/bash-completion/completions/ruff
          - $PREFIX/bin/ruff generate-shell-completion fish > $PREFIX/share/fish/vendor_completions.d/ruff.fish

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - if: unix
      then: make

tests:
  - package_contents:
      bin:
        - ruff
      files:
        - if: unix
          then:
            - share/bash-completion/completions/ruff
            - share/fish/vendor_completions.d/ruff.fish
            - share/zsh/site-functions/_ruff
      strict: true
  - script:
      - ruff --version
      - ruff --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An extremely fast Python linter, written in Rust.
  description: |
    An extremely fast Python linter, written in Rust. Ruff can be used to
    replace Flake8 (plus a variety of plugins), isort, pydocstyle, yesqa, and
    even a subset of pyupgrade and autoflake all while executing tens or
    hundreds of times faster than any individual tool.
  homepage: https://github.com/astral-sh/ruff
  documentation: https://docs.astral.sh/ruff
  repository: https://github.com/astral-sh/ruff

extra:
  recipe-maintainers:
    - dhruvmanila
    - ntBre
    - zanieb
    - messense
    - charliermarsh
